apiVersion: v1
kind: ConfigMap
metadata:
  name: order-system-config
  namespace: order-system
data:
  KAFKA_BROKER: "kafka:29092"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "orderuser"
  POSTGRES_DB: "orderdb"
  POSTGRES_DB_INVENTORY: "inventorydb"
  POSTGRES_DB_ANALYTICS: "analyticsdb"
  POSTGRES_DB_AUDIT: "auditdb"
  POSTGRES_DB_PAYMENT: "paymentdb"
  POSTGRES_DB_DLQ: "dlqdb"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  NODE_ENV: "production"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: order-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "order-service"
        static_configs:
          - targets: ["order-service:4001"]
      - job_name: "inventory-service"
        static_configs:
          - targets: ["inventory-service:4002"]
      - job_name: "notification-service"
        static_configs:
          - targets: ["notification-service:4003"]
      - job_name: "analytics-service"
        static_configs:
          - targets: ["analytics-service:4004"]
      - job_name: "audit-service"
        static_configs:
          - targets: ["audit-service:4005"]
      - job_name: "payment-service"
        static_configs:
          - targets: ["payment-service:4006"]
      - job_name: "dlq-replay-service"
        static_configs:
          - targets: ["dlq-replay-service:4007"]
