apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-system-ingress
  namespace: order-system
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: orders.example.com
      http:
        paths:
          - path: /api(/orders|/inventory|/analytics|/audit)(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 4001
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 3000
