apiVersion: v1
kind: Secret
metadata:
  name: order-system-secrets
  namespace: order-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "orderpass"
  JWT_SECRET: "change-me-in-production"
  REDIS_PASSWORD: ""
  GRAFANA_ADMIN_PASSWORD: "admin"
